# Generated by Django 6.0 on 2025-12-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0002_product_productcategory_fertilizerdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alluser',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
