# Generated by Django 6.0 on 2025-12-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0003_alluser_reset_token_alluser_reset_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alluser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alluser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
