# Generated by Django 6.0 on 2025-12-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0004_alluser_gst_number_alluser_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
