# Generated by Django 6.0 on 2025-12-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0005_alluser_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizerdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seeddetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='EquipmentDetail',
        ),
        migrations.DeleteModel(
            name='FertilizerDetail',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SeedDetail',
        ),
    ]
