# Generated by Django 6.0 on 2025-12-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0006_remove_fertilizerdetail_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
