# Generated by Django 6.0 on 2025-12-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0007_farmerprofile_latitude_farmerprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
