# Generated by Django 6.0 on 2025-12-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0008_alter_farmerprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alluser',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='alluser',
            name='shop_name',
        ),
    ]
