# Generated by Django 6.0 on 2026-01-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0009_remove_alluser_gst_number_remove_alluser_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='crop',
            field=models.CharField(blank=True, choices=[('rice', 'Rice'), ('wheat', 'Wheat'), ('maize', 'Maize'), ('barley', 'Barley'), ('oats', 'Oats'), ('sorghum', 'Sorghum (Jowar)'), ('millet', 'Millet (Bajra)'), ('ragi', 'Ragi'), ('gram', 'Chickpea (Gram)'), ('pigeon_pea', 'Pigeon Pea (Toor Dal)'), ('lentil', 'Lentil (Masoor)'), ('mung', 'Green Gram (Moong)'), ('urad', 'Black Gram (Urad)'), ('pea', 'Pea'), ('mustard', 'Mustard'), ('groundnut', 'Groundnut'), ('sunflower', 'Sunflower'), ('soybean', 'Soybean'), ('sesame', 'Sesame (Til)'), ('castor', 'Castor'), ('cotton', 'Cotton'), ('jute', 'Jute'), ('sugarcane', 'Sugarcane'), ('tobacco', 'Tobacco'), ('potato', 'Potato'), ('onion', 'Onion'), ('tomato', 'Tomato'), ('chilli', 'Chilli'), ('cabbage', 'Cabbage'), ('cauliflower', 'Cauliflower'), ('brinjal', 'Brinjal'), ('okra', 'Okra'), ('banana', 'Banana'), ('mango', 'Mango'), ('grapes', 'Grapes'), ('orange', 'Orange'), ('pomegranate', 'Pomegranate'), ('apple', 'Apple'), ('papaya', 'Papaya')], max_length=30, null=True),
        ),
    ]
