# Generated by Django 6.0 on 2026-01-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0009_remove_alluser_gst_number_remove_alluser_shop_name'),
        ('markets', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketcart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketcart',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_carts', to='farmersaccapp.buyerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='marketcart',
            unique_together={('farmer', 'market', 'buyer')},
        ),
    ]
