# Generated by Django 6.0 on 2026-01-04 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0009_remove_alluser_gst_number_remove_alluser_shop_name'),
        ('trading', '0002_alter_marketcart_unique_together_marketcart_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_carts', to='farmersaccapp.buyerprofile'),
        ),
    ]
