# Generated by Django 6.0 on 2026-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_marketcart_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsellorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
