# Generated by Django 6.0 on 2026-01-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_farmernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmernotification',
            name='title',
        ),
        migrations.AddField(
            model_name='farmernotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.marketsellorder'),
        ),
    ]
