# Generated by Django 6.0 on 2026-01-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerbuyprice',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_buy_prices', to='markets.market'),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='unit',
            field=models.CharField(default='kg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
