# Generated by Django 6.0 on 2026-01-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0002_buyerbuyprice_market_alter_buyerbuyprice_is_active_and_more'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_buy_prices', to='markets.market'),
        ),
    ]
