# Generated by Django 6.0 on 2026-01-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0003_alter_buyerbuyprice_market'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersellproduct',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_sell_products', to='markets.market'),
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='unit',
            field=models.CharField(default='kg', max_length=20, null=True),
        ),
    ]
