# Generated by Django 6.0 on 2026-01-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0004_buyersellproduct_market_and_more'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyersellproduct',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_sell_products', to='markets.market'),
        ),
    ]
