# Generated by Django 6.0 on 2026-01-03 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0005_alter_buyersellproduct_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyerbuyprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyersellproduct',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
