# Generated by Django 6.0 on 2026-01-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0006_alter_buyerbuyprice_is_active_and_more'),
        ('farmersaccapp', '0009_remove_alluser_gst_number_remove_alluser_shop_name'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_carts', to='farmersaccapp.farmerprofile')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='markets.market')),
            ],
            options={
                'unique_together': {('farmer', 'market')},
            },
        ),
        migrations.CreateModel(
            name='MarketCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('buyer_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyersapp.buyerbuyprice')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buyersapp.marketcart')),
            ],
        ),
    ]
