# Generated by Django 6.0 on 2026-01-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0007_marketcart_marketcartitem'),
        ('farmersaccapp', '0009_remove_alluser_gst_number_remove_alluser_shop_name'),
        ('markets', '0001_initial'),
        ('products', '0002_marketproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersaccapp.buyerprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersaccapp.farmerprofile')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='MarketSellOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buyersapp.marketsellorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
