# Generated by Django 6.0 on 2026-01-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0008_marketsellorder_marketsellorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketcartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='marketcartitem',
            name='buyer_price',
        ),
        migrations.RemoveField(
            model_name='marketsellorder',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='marketsellorder',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='marketsellorder',
            name='market',
        ),
        migrations.RemoveField(
            model_name='marketsellorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='marketsellorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='MarketCart',
        ),
        migrations.DeleteModel(
            name='MarketCartItem',
        ),
        migrations.DeleteModel(
            name='MarketSellOrder',
        ),
        migrations.DeleteModel(
            name='MarketSellOrderItem',
        ),
    ]
