# Generated by Django 6.0 on 2026-01-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0009_remove_marketcartitem_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellRequest',
        ),
    ]
