# Generated by Django 6.0 on 2026-01-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersaccapp', '0009_remove_alluser_gst_number_remove_alluser_shop_name'),
        ('markets', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='markets.market'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='farmersaccapp.alluser'),
        ),
    ]
