# Generated by Django 6.0 on 2026-01-04 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('orders', '0002_cart_market_alter_cart_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.market'),
        ),
    ]
